services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test123!"
      MSSQL_PID: "Express"
    ports: 
      - "1433:1433"
  api:
    build: .
    environment:
      DBServer: "ms-sql-server"
      DBPort: "1433"
      DBUser: "sa"
      DBPassword: "Test123!"
      Database: "MachinesDB"
    ports: 
      - "8080:80"